# Generated by Django 2.0.5 on 2018-06-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listatelefonica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='phoneent',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone Entidade'),
        ),
        migrations.AddField(
            model_name='phonebook',
            name='phonesec',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone Secundario'),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='ramal',
            field=models.CharField(blank=True, max_length=10, verbose_name='Ramal'),
        ),
    ]
