# Generated by Django 2.0.5 on 2018-06-08 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listatelefonica', '0003_auto_20180608_0954'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstype',
            options={'verbose_name': 'Tipo de Acesso', 'verbose_name_plural': 'Tipos de Acesso'},
        ),
        migrations.AddField(
            model_name='access',
            name='identifier',
            field=models.CharField(default=1, max_length=35, verbose_name='Identificador'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='access',
            name='password',
            field=models.CharField(blank=True, max_length=35, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='access',
            name='accesstype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='listatelefonica.AccessType', verbose_name='Tipo de Acesso'),
        ),
        migrations.AlterField(
            model_name='access',
            name='description',
            field=models.CharField(max_length=35, verbose_name='Identificador'),
        ),
    ]
