# Generated by Django 2.0.5 on 2018-06-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listatelefonica', '0004_auto_20180608_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='description',
            field=models.CharField(max_length=50, verbose_name='Descrição'),
        ),
    ]
