# Generated by Django 2.0.5 on 2018-06-13 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listatelefonica', '0006_auto_20180608_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonebook',
            name='lastname',
            field=models.CharField(blank=True, max_length=150, verbose_name='SobreNome'),
        ),
        migrations.AlterField(
            model_name='phonebook',
            name='role',
            field=models.CharField(blank=True, max_length=20, verbose_name='Cargo'),
        ),
    ]
