# Generated by Django 2.0.5 on 2018-06-14 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listatelefonica', '0007_auto_20180613_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phonebook',
            options={'ordering': ['name'], 'verbose_name': 'Contato', 'verbose_name_plural': 'Contatos'},
        ),
        migrations.AddField(
            model_name='phonebook',
            name='department',
            field=models.CharField(blank=True, max_length=20, verbose_name='Setor'),
        ),
    ]
